import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import fs from 'node:fs/promises';
import { BeatmapDownloads, validateBeatmap, zipIndex } from './lib/beatmap-download.mjs';
const content = Buffer.from('osu file format v14\n[Metadata]\nBeatmapID:123\nBeatmapSetID:456\n');
const name = Buffer.from('Fixture [7K].osu');
const header = Buffer.alloc(30); header.writeUInt32LE(0x04034b50); header.writeUInt16LE(name.length,26);
const directory = Buffer.alloc(46); directory.writeUInt32LE(0x02014b50);
directory.writeUInt32LE(content.length,20); directory.writeUInt32LE(content.length,24); directory.writeUInt16LE(name.length,28);
const start = header.length + name.length + content.length;
const end = Buffer.alloc(22); end.writeUInt32LE(0x06054b50); end.writeUInt16LE(1,8); end.writeUInt16LE(1,10);
end.writeUInt32LE(directory.length+name.length,12); end.writeUInt32LE(start,16);
const archive = Buffer.concat([header,name,content,directory,name,end]);
const entry={beatmap_id:123,beatmapset_id:456,difficulty:'7K',checksum:createHash('md5').update(content).digest('hex')};
const source={gaps:{},async cached(k,t,loader){return loader();},async request(url,options){
  const [a,b]=options.headers.Range.slice(6).split('-');
  const first=a===''?Math.max(0,archive.length-Number(b)):Number(a);
  const last=a===''?archive.length-1:Math.min(Number(b),archive.length-1);
  return {bytes:archive.subarray(first,last+1),url,range:`bytes ${first}-${last}/${archive.length}`};
}};
const downloads=new BeatmapDownloads(source,2);
assert.deepEqual(await downloads.mirror(entry),content);
assert.throws(()=>validateBeatmap(content,{...entry,checksum:'invalid'}));
assert.throws(()=>validateBeatmap(content,{...entry,beatmap_id:124}));
assert.throws(()=>zipIndex(Buffer.from('not a zip')));
downloads.mirror=async()=>{throw new Error('stale mirror');};
source.request=async()=>content;
assert.deepEqual(await downloads.download(entry),content);
assert.equal(downloads.metrics.fallback,1);
const controller=new AbortController();controller.abort();
await assert.rejects(downloads.download(entry,controller.signal));
const local=`data/local-seed-test-${Date.now()}`;
await fs.mkdir(local,{recursive:true}); await fs.writeFile(`${local}/123.osu`,content);
source.localBeatmapDirectory=local;
source.request=async()=>assert.fail('Valid local seed should avoid network requests');
assert.deepEqual(await downloads.download(entry),content);
assert.equal(downloads.metrics.local,1);
console.log('Range ZIP extraction, identity/hash validation, fallback, cancellation and local seed passed.');
